clear ; cat lang_tcl86/options ; read
clear ; cat graphics_jasper/options ; read
clear ; cat dns_p5-Net-DNS/options ; read
clear ; cat devel_p5-DateTime-locale/options ; read
clear ; cat www_p5-libwww/options ; read
clear ; cat devel_p5-DateTimeZone/options ; read
clear ; cat devel_p5-DateTime/options ; read
clear ; cat devel_libevent2/options ; read
clear ; cat sysutils_tmux/options ; read
clear ; cat www_lynx/options ; read
clear ; cat security_nmap/options ; read
clear ; cat print_freetype2/options ; read
clear ; cat dns_libidn/options ; read
clear ; cat devel_glib20/options ; read
clear ; cat ftp_wget/options ; read
clear ; cat math_gmp/options ; read
clear ; cat print_cups-client/options ; read
clear ; cat databases_postgresql93-client/options ; read
clear ; cat security_libtasn1/options ; read
clear ; cat databases_sqlite3/options ; read
clear ; cat textproc_py-pygments/options ; read
clear ; cat textproc_py-docutils/options ; read
clear ; cat x11-fonts_fontconfig/options ; read
clear ; cat x11-fonts_dejavu/options ; read
clear ; cat security_nettle/options ; read
clear ; cat devel_libcheck/options ; read
clear ; cat x11_libxcb/options ; read
clear ; cat devel_py-babel/options ; read
clear ; cat devel_icu/options ; read
clear ; cat devel_py-Jinja2/options ; read
clear ; cat security_pinentry/options ; read
clear ; cat security_trousers/options ; read
clear ; cat security_gnutls/options ; read
clear ; cat security_gnupg/options ; read
clear ; cat shells_bash-completion/options ; read
clear ; cat devel_cmake/options ; read
clear ; cat sysutils_munin-node/options ; read
clear ; cat graphics_png/options ; read
clear ; cat graphics_cairo/options ; read
clear ; cat graphics_gdk-pixbuf2/options ; read
clear ; cat editors_vim/options ; read
clear ; cat databases_gdbm/options ; read
clear ; cat devel_apr1/options ; read
clear ; cat www_serf/options ; read
clear ; cat devel_subversion/options ; read
