#!/bin/sh
# run as root - ports tree needed
portsnap fetch extract
cd /usr/ports/ports-mgmt/portconf && make install clean
pkg install git python gmake automake libtool
pkg delete git-\*

mkdir /var/db/ports/devel_git
mkdir /var/db/ports/textproc_xmlto
mkdir /var/db/ports/shells_bash
mkdir /var/db/ports/devel_bison
mkdir /var/db/ports/devel_m4
mkdir /var/db/ports/devel_gettext-tools
mkdir /var/db/ports/lang_perl5.20
mkdir /var/db/ports/misc_getopt
mkdir /var/db/ports/devel_gmake
mkdir /var/db/ports/textproc_libxml2
mkdir /var/db/ports/textproc_libxslt
mkdir /var/db/ports/security_libgcrypt
mkdir /var/db/ports/security_libgpg-error
mkdir /var/db/ports/textproc_docbook-xsl
mkdir /var/db/ports/textproc_xmlcatmgr
mkdir /var/db/ports/www_w3m
mkdir /var/db/ports/devel_boehm-gc
##mkdir /var/db/ports/devel_libatomic_ops
mkdir /var/db/ports/lang_python27
mkdir /var/db/ports/devel_libffi
mkdir /var/db/ports/ftp_curl
mkdir /var/db/ports/security_ca_root_nss
mkdir /var/db/ports/devel_cvsps
mkdir /var/db/ports/security_p5-IO-Socket-SSL
mkdir /var/db/ports/security_p5-Net-SSLeay
mkdir /var/db/ports/security_p5-Authen-SASL
mkdir /var/db/ports/security_p5-GSSAPI
mkdir /var/db/ports/devel_apr1
mkdir /var/db/ports/databases_gdbm
mkdir /var/db/ports/databases_db5
mkdir /var/db/ports/databases_sqlite3
mkdir /var/db/ports/devel_subversion
mkdir /var/db/ports/www_serf
mkdir /var/db/ports/print_texinfo

## Update 1
cat << EOF > /var/db/ports/devel_git/options
_OPTIONS_READ=git-2.9.0
_FILE_COMPLETE_OPTIONS_LIST=CONTRIB CURL CVS GITWEB GUI HTMLDOCS ICONV NLS P4 PERL SEND_EMAIL SVN
OPTIONS_FILE_SET+=CONTRIB
OPTIONS_FILE_SET+=CURL
OPTIONS_FILE_SET+=CVS
OPTIONS_FILE_UNSET+=GITWEB
OPTIONS_FILE_UNSET+=GUI
OPTIONS_FILE_UNSET+=HTMLDOCS
OPTIONS_FILE_SET+=ICONV
OPTIONS_FILE_SET+=NLS
OPTIONS_FILE_SET+=P4
OPTIONS_FILE_SET+=PERL
OPTIONS_FILE_SET+=SEND_EMAIL
OPTIONS_FILE_SET+=SVN
EOF

## Update 2
cat << EOF > /var/db/ports/textproc_xmlto/options
_OPTIONS_READ=xmlto-0.0.28
_FILE_COMPLETE_OPTIONS_LIST=DOCS DBLATEX FOP PASSIVETEX
OPTIONS_FILE_SET+=DOCS
OPTIONS_FILE_UNSET+=DBLATEX
OPTIONS_FILE_UNSET+=FOP
OPTIONS_FILE_UNSET+=PASSIVETEX
EOF

## Update 3
cat << EOF > /var/db/ports/shells_bash/options
_OPTIONS_READ=bash-4.3.46_1
_FILE_COMPLETE_OPTIONS_LIST=COLONBREAKSWORDS DOCS HELP IMPLICITCD IMPORTFUNCTIONS NLS STATIC SYSLOG
OPTIONS_FILE_SET+=COLONBREAKSWORDS
OPTIONS_FILE_SET+=DOCS
OPTIONS_FILE_SET+=HELP
OPTIONS_FILE_SET+=IMPLICITCD
OPTIONS_FILE_UNSET+=IMPORTFUNCTIONS
OPTIONS_FILE_SET+=NLS
OPTIONS_FILE_UNSET+=STATIC
OPTIONS_FILE_UNSET+=SYSLOG
EOF

# Update 4
cat << EOF > /var/db/ports/devel_bison/options
_OPTIONS_READ=bison-2.7.1,1
_FILE_COMPLETE_OPTIONS_LIST=EXAMPLES NLS
OPTIONS_FILE_SET+=EXAMPLES
OPTIONS_FILE_SET+=NLS
EOF

# Update 6
cat << EOF > /var/db/ports/devel_gettext-tools/options
_OPTIONS_READ=gettext-tools-0.19.8.1
_FILE_COMPLETE_OPTIONS_LIST=DOCS THREADS
OPTIONS_FILE_SET+=DOCS
OPTIONS_FILE_SET+=THREADS
EOF

# Update 5
cat << EOF > /var/db/ports/devel_m4/options
_OPTIONS_READ=m4-1.4.17_1,1
_FILE_COMPLETE_OPTIONS_LIST=EXAMPLES LIBSIGSEGV
OPTIONS_FILE_SET+=EXAMPLES
OPTIONS_FILE_UNSET+=LIBSIGSEGV
EOF

# Update 6
cat << EOF > /var/db/ports/lang_perl5.20/options
_OPTIONS_READ=perl5-5.20.3_13
_FILE_COMPLETE_OPTIONS_LIST=DEBUG GDBM MULTIPLICITY PERL_64BITINT PTHREAD SITECUSTOMIZE THREADS PERL_MALLOC
OPTIONS_FILE_UNSET+=DEBUG
OPTIONS_FILE_UNSET+=GDBM
OPTIONS_FILE_SET+=MULTIPLICITY
OPTIONS_FILE_SET+=PERL_64BITINT
OPTIONS_FILE_SET+=PTHREAD
OPTIONS_FILE_UNSET+=SITECUSTOMIZE
OPTIONS_FILE_SET+=THREADS
OPTIONS_FILE_UNSET+=PERL_MALLOC
EOF

# Update 7
cat << EOF > /var/db/ports/misc_getopt/options
_OPTIONS_READ=getopt-1.1.6
_FILE_COMPLETE_OPTIONS_LIST=DOCS NLS
OPTIONS_FILE_SET+=DOCS
OPTIONS_FILE_SET+=NLS
EOF

# Update 8
cat << EOF > /var/db/ports/devel_gmake/options
_OPTIONS_READ=gmake-4.2.1
_FILE_COMPLETE_OPTIONS_LIST=NLS
OPTIONS_FILE_SET+=NLS
EOF

# Update 9
cat << EOF > /var/db/ports/textproc_libxml2/options
_OPTIONS_READ=libxml2-2.9.3
_FILE_COMPLETE_OPTIONS_LIST=MEM_DEBUG SCHEMA THREADS THREAD_ALLOC VALID XMLLINT_HIST
OPTIONS_FILE_UNSET+=MEM_DEBUG
OPTIONS_FILE_SET+=SCHEMA
OPTIONS_FILE_SET+=THREADS
OPTIONS_FILE_UNSET+=THREAD_ALLOC
OPTIONS_FILE_SET+=VALID
OPTIONS_FILE_UNSET+=XMLLINT_HIST
EOF

# Update 10
cat << EOF > /var/db/ports/textproc_libxslt/options
_OPTIONS_READ=libxslt-1.1.29
_FILE_COMPLETE_OPTIONS_LIST=CRYPTO MEM_DEBUG
OPTIONS_FILE_SET+=CRYPTO
OPTIONS_FILE_UNSET+=MEM_DEBUG
EOF

# Update 11
cat << EOF > /var/db/ports/security_libgcrypt/options
_OPTIONS_READ=libgcrypt-1.7.1
_FILE_COMPLETE_OPTIONS_LIST=DOCS
OPTIONS_FILE_SET+=DOCS
EOF

# Update 12
cat << EOF > /var/db/ports/security_libgpg-error/options
_OPTIONS_READ=libgpg-error-1.23
_FILE_COMPLETE_OPTIONS_LIST=DOCS NLS
OPTIONS_FILE_SET+=DOCS
OPTIONS_FILE_SET+=NLS
EOF

# Update 13
cat << EOF > /var/db/ports/textproc_docbook-xsl/options
_OPTIONS_READ=docbook-xsl-1.76.1_3
_FILE_COMPLETE_OPTIONS_LIST=DOCS ECLIPSE EPUB EXTENSIONS HIGHLIGHTING HTMLHELP JAVAHELP PROFILING ROUNDTRIP SLIDES TEMPLATE TESTS TOOLS WEBSITE XHTML11
OPTIONS_FILE_SET+=DOCS
OPTIONS_FILE_SET+=ECLIPSE
OPTIONS_FILE_SET+=EPUB
OPTIONS_FILE_SET+=EXTENSIONS
OPTIONS_FILE_SET+=HIGHLIGHTING
OPTIONS_FILE_SET+=HTMLHELP
OPTIONS_FILE_SET+=JAVAHELP
OPTIONS_FILE_SET+=PROFILING
OPTIONS_FILE_SET+=ROUNDTRIP
OPTIONS_FILE_SET+=SLIDES
OPTIONS_FILE_SET+=TEMPLATE
OPTIONS_FILE_SET+=TESTS
OPTIONS_FILE_SET+=TOOLS
OPTIONS_FILE_SET+=WEBSITE
OPTIONS_FILE_SET+=XHTML11
EOF

# Update 14
cat << EOF > /var/db/ports/textproc_xmlcatmgr/options
_OPTIONS_READ=xmlcatmgr-2.2_2
_FILE_COMPLETE_OPTIONS_LIST=DOCS
OPTIONS_FILE_SET+=DOCS
EOF

# Update 15
cat << EOF > /var/db/ports/www_w3m/options
_OPTIONS_READ=w3m-0.5.3_5
_FILE_COMPLETE_OPTIONS_LIST=DOCS INLINE_IMAGE JAPANESE KEY_LYNX
OPTIONS_FILE_SET+=DOCS
OPTIONS_FILE_UNSET+=INLINE_IMAGE
OPTIONS_FILE_UNSET+=JAPANESE
OPTIONS_FILE_UNSET+=KEY_LYNX
EOF

# Update 16
cat << EOF > /var/db/ports/devel_boehm-gc/options
_OPTIONS_READ=boehm-gc-7.4.4
_FILE_COMPLETE_OPTIONS_LIST=DEBUG DOCS
OPTIONS_FILE_UNSET+=DEBUG
OPTIONS_FILE_SET+=DOCS
EOF

# Update 17
cat << EOF > /var/db/ports/lang_python27/options
_OPTIONS_READ=python27-2.7.11_3
_FILE_COMPLETE_OPTIONS_LIST=DEBUG IPV6 LIBFFI NLS PYMALLOC SEM THREADS UCS2 UCS4
OPTIONS_FILE_UNSET+=DEBUG
OPTIONS_FILE_SET+=IPV6
OPTIONS_FILE_SET+=LIBFFI
OPTIONS_FILE_SET+=NLS
OPTIONS_FILE_SET+=PYMALLOC
OPTIONS_FILE_SET+=SEM
OPTIONS_FILE_SET+=THREADS
OPTIONS_FILE_UNSET+=UCS2
OPTIONS_FILE_SET+=UCS4
EOF

# Update 18
cat << EOF > /var/db/ports/devel_libffi/options
_OPTIONS_READ=libffi-3.2.1
_FILE_COMPLETE_OPTIONS_LIST=TESTS
OPTIONS_FILE_UNSET+=TESTS
EOF

# Update 19
cat << EOF > /var/db/ports/ftp_curl/options
_OPTIONS_READ=curl-7.49.1
_FILE_COMPLETE_OPTIONS_LIST=CA_BUNDLE COOKIES CURL_DEBUG DEBUG DOCS EXAMPLES HTTP2 IDN IPV6 LDAP LDAPS LIBSSH2 METALINK PROXY PSL RTMP TLS_SRP GSSAPI_BASE GSSAPI_HEIMDAL GSSAPI_MIT GSSAPI_NONE CARES THREADED_RESOLVER GNUTLS NSS OPENSSL POLARSSL WOLFSSL
OPTIONS_FILE_SET+=CA_BUNDLE
OPTIONS_FILE_SET+=COOKIES
OPTIONS_FILE_UNSET+=CURL_DEBUG
OPTIONS_FILE_UNSET+=DEBUG
OPTIONS_FILE_SET+=DOCS
OPTIONS_FILE_SET+=EXAMPLES
OPTIONS_FILE_UNSET+=HTTP2
OPTIONS_FILE_UNSET+=IDN
OPTIONS_FILE_SET+=IPV6
OPTIONS_FILE_UNSET+=LDAP
OPTIONS_FILE_UNSET+=LDAPS
OPTIONS_FILE_UNSET+=LIBSSH2
OPTIONS_FILE_UNSET+=METALINK
OPTIONS_FILE_SET+=PROXY
OPTIONS_FILE_UNSET+=PSL
OPTIONS_FILE_UNSET+=RTMP
OPTIONS_FILE_SET+=TLS_SRP
OPTIONS_FILE_SET+=GSSAPI_BASE
OPTIONS_FILE_UNSET+=GSSAPI_HEIMDAL
OPTIONS_FILE_UNSET+=GSSAPI_MIT
OPTIONS_FILE_UNSET+=GSSAPI_NONE
OPTIONS_FILE_UNSET+=CARES
OPTIONS_FILE_SET+=THREADED_RESOLVER
OPTIONS_FILE_UNSET+=GNUTLS
OPTIONS_FILE_UNSET+=NSS
OPTIONS_FILE_SET+=OPENSSL
OPTIONS_FILE_UNSET+=POLARSSL
OPTIONS_FILE_UNSET+=WOLFSSL
EOF

# Update 20
cat << EOF > /var/db/ports/security_ca_root_nss/options
_OPTIONS_READ=ca_root_nss-3.25
_FILE_COMPLETE_OPTIONS_LIST=ETCSYMLINK
OPTIONS_FILE_SET+=ETCSYMLINK
EOF

# Update 21
cat << EOF > /var/db/ports/devel_cvsps/options
_OPTIONS_READ=cvsps-2.1_1
_FILE_COMPLETE_OPTIONS_LIST=DOCS
OPTIONS_FILE_SET+=DOCS
EOF

# Update 22
cat << EOF > /var/db/ports/security_p5-IO-Socket-SSL/options
_OPTIONS_READ=p5-IO-Socket-SSL-2.029
_FILE_COMPLETE_OPTIONS_LIST=EXAMPLES IDN IPV6
OPTIONS_FILE_SET+=EXAMPLES
OPTIONS_FILE_UNSET+=IDN
OPTIONS_FILE_SET+=IPV6
EOF

# Update 23
cat << EOF > /var/db/ports/security_p5-Net-SSLeay/options
_OPTIONS_READ=p5-Net-SSLeay-1.74
_FILE_COMPLETE_OPTIONS_LIST=EXAMPLES
OPTIONS_FILE_SET+=EXAMPLES
EOF

# Update 24
cat << EOF > /var/db/ports/security_p5-Authen-SASL/options
_OPTIONS_READ=p5-Authen-SASL-2.16_1
_FILE_COMPLETE_OPTIONS_LIST=KERBEROS
OPTIONS_FILE_SET+=KERBEROS
EOF

# Update 25
cat << EOF > /var/db/ports/security_p5-GSSAPI/options
_OPTIONS_READ=p5-GSSAPI-0.28_1
_FILE_COMPLETE_OPTIONS_LIST= GSSAPI_BASE GSSAPI_HEIMDAL GSSAPI_MIT
OPTIONS_FILE_SET+=GSSAPI_BASE
OPTIONS_FILE_UNSET+=GSSAPI_HEIMDAL
OPTIONS_FILE_UNSET+=GSSAPI_MIT
EOF

# Update 26
cat << EOF > /var/db/ports/devel_apr1/options
_OPTIONS_READ=apr-1.5.2.1.5.4
_FILE_COMPLETE_OPTIONS_LIST= SSL NSS IPV6 DEVRANDOM BDB GDBM LDAP MYSQL NDBM PGSQL SQLITE FREETDS
OPTIONS_FILE_SET+=SSL
OPTIONS_FILE_UNSET+=NSS
OPTIONS_FILE_SET+=IPV6
OPTIONS_FILE_SET+=DEVRANDOM
OPTIONS_FILE_SET+=BDB
OPTIONS_FILE_SET+=GDBM
OPTIONS_FILE_UNSET+=LDAP
OPTIONS_FILE_UNSET+=MYSQL
OPTIONS_FILE_UNSET+=NDBM
OPTIONS_FILE_UNSET+=PGSQL
OPTIONS_FILE_UNSET+=SQLITE
OPTIONS_FILE_UNSET+=FREETDS
EOF

# Update 27
cat << EOF > /var/db/ports/databases_gdbm/options
_OPTIONS_READ=gdbm-1.12
_FILE_COMPLETE_OPTIONS_LIST=COMPAT NLS
OPTIONS_FILE_UNSET+=COMPAT
OPTIONS_FILE_SET+=NLS
EOF

# Update 28
cat << EOF > /var/db/ports/databases_db5/options
_OPTIONS_READ=db5-5.3.28_4
_FILE_COMPLETE_OPTIONS_LIST=CRYPTO DOCS JAVA L10N SQL TCL
OPTIONS_FILE_SET+=CRYPTO
OPTIONS_FILE_SET+=DOCS
OPTIONS_FILE_UNSET+=JAVA
OPTIONS_FILE_UNSET+=L10N
OPTIONS_FILE_UNSET+=SQL
OPTIONS_FILE_UNSET+=TCL
EOF

# Update 29
cat << EOF > /var/db/ports/databases_sqlite3/options
_OPTIONS_READ=sqlite3-3.13.0
_FILE_COMPLETE_OPTIONS_LIST=ARMOR DBSTAT DIRECT_READ EXTENSION FTS3_TOKEN FTS4 FTS5 JSON1 LIKENOTBLOB MEMMAN METADATA RBU SECURE_DELETE SESSION SOUNDEX STMT STSHELL THREADS UNLOCK_NOTIFY UPD_DEL_LIMIT URI URI_AUTHORITY TS0 TS1 TS2 TS3 STAT3 STAT4 ICU UNICODE61 RTREE RTREE_INT READLINES READLINEP EDITLINE
OPTIONS_FILE_UNSET+=ARMOR
OPTIONS_FILE_SET+=DBSTAT
OPTIONS_FILE_UNSET+=DIRECT_READ
OPTIONS_FILE_SET+=EXTENSION
OPTIONS_FILE_SET+=FTS3_TOKEN
OPTIONS_FILE_SET+=FTS4
OPTIONS_FILE_UNSET+=FTS5
OPTIONS_FILE_UNSET+=JSON1
OPTIONS_FILE_UNSET+=LIKENOTBLOB
OPTIONS_FILE_UNSET+=MEMMAN
OPTIONS_FILE_SET+=METADATA
OPTIONS_FILE_UNSET+=RBU
OPTIONS_FILE_SET+=SECURE_DELETE
OPTIONS_FILE_UNSET+=SESSION
OPTIONS_FILE_UNSET+=SOUNDEX
OPTIONS_FILE_UNSET+=STMT
OPTIONS_FILE_SET+=STSHELL
OPTIONS_FILE_SET+=THREADS
OPTIONS_FILE_SET+=UNLOCK_NOTIFY
OPTIONS_FILE_UNSET+=UPD_DEL_LIMIT
OPTIONS_FILE_SET+=URI
OPTIONS_FILE_UNSET+=URI_AUTHORITY
OPTIONS_FILE_UNSET+=TS0
OPTIONS_FILE_SET+=TS1
OPTIONS_FILE_UNSET+=TS2
OPTIONS_FILE_UNSET+=TS3
OPTIONS_FILE_UNSET+=STAT3
OPTIONS_FILE_UNSET+=STAT4
OPTIONS_FILE_UNSET+=ICU
OPTIONS_FILE_SET+=UNICODE61
OPTIONS_FILE_SET+=RTREE
OPTIONS_FILE_UNSET+=RTREE_INT
OPTIONS_FILE_SET+=READLINES
OPTIONS_FILE_UNSET+=READLINEP
OPTIONS_FILE_UNSET+=EDITLINE
EOF

# Update 30
cat << EOF > /var/db/ports/devel_subversion/options
_OPTIONS_READ=subversion-1.9.4
_FILE_COMPLETE_OPTIONS_LIST=BDB DOCS FREEBSD_TEMPLATE MAINTAINER_DEBUG NLS SASL SERF STATIC SVNSERVE_WRAPPER TEST TOOLS
OPTIONS_FILE_UNSET+=BDB
OPTIONS_FILE_SET+=DOCS
OPTIONS_FILE_SET+=FREEBSD_TEMPLATE
OPTIONS_FILE_UNSET+=MAINTAINER_DEBUG
OPTIONS_FILE_SET+=NLS
OPTIONS_FILE_UNSET+=SASL
OPTIONS_FILE_SET+=SERF
OPTIONS_FILE_UNSET+=STATIC
OPTIONS_FILE_UNSET+=SVNSERVE_WRAPPER
OPTIONS_FILE_UNSET+=TEST
OPTIONS_FILE_SET+=TOOLS
EOF

# Update 31
cat << EOF > /var/db/ports/www_serf/options
_OPTIONS_READ=serf-1.3.8_1
_FILE_COMPLETE_OPTIONS_LIST=DOCS MIT HEIMDAL HEIMDAL_BASE
OPTIONS_FILE_SET+=DOCS
OPTIONS_FILE_UNSET+=MIT
OPTIONS_FILE_UNSET+=HEIMDAL
OPTIONS_FILE_UNSET+=HEIMDAL_BASE
EOF

# Update 32
##mkdir /var/db/ports/print_texinfo

## Add libatomic

echo "devel/subversion: WITHOUT_MOD_DAV_SVN|WITHOUT_APACHE2_APR" >> /usr/local/etc/ports.conf
echo "devel/apr-svn: APR_UTIL_WITH_BERKELEY_DB=yes" >> /usr/local/etc/ports.conf

cd /usr/ports/devel/git && make install clean
