#!/bin/sh
# run as root - ports tree needed
cd /usr/ports/ports-mgmt/portconf && make install clean
pkg_add -r git python gmake automake14 libtool
pkg_delete git-\*
##pkg_delete \*-freebsd-doc-\*
##pkg_add -r en-freebsd-doc fr-freebsd-doc de-freebsd-doc
# if this fails: portsnap fetch extract

mkdir /var/db/ports/python27
mkdir /var/db/ports/libiconv
mkdir /var/db/ports/git
mkdir /var/db/ports/perl
mkdir /var/db/ports/curl
mkdir /var/db/ports/ca_root_nss
mkdir /var/db/ports/pcre

cat << EOF > /var/db/ports/python27/options
_OPTIONS_READ=python27-2.7.3_6
_FILE_COMPLETE_OPTIONS_LIST=EXAMPLES FPECTL IPV6 NLS PTH PYMALLOC SEM THREADS UCS2 UCS4
OPTIONS_FILE_SET+=EXAMPLES
OPTIONS_FILE_UNSET+=FPECTL
OPTIONS_FILE_SET+=IPV6
OPTIONS_FILE_SET+=NLS
OPTIONS_FILE_UNSET+=PTH
OPTIONS_FILE_SET+=PYMALLOC
OPTIONS_FILE_UNSET+=SEM
OPTIONS_FILE_SET+=THREADS
OPTIONS_FILE_UNSET+=UCS2
OPTIONS_FILE_SET+=UCS4
EOF

cat << EOF > /var/db/ports/libiconv/options
_OPTIONS_READ=libiconv-1.14
_FILE_COMPLETE_OPTIONS_LIST=ENCODINGS PATCHES
OPTIONS_FILE_SET+=ENCODINGS
OPTIONS_FILE_UNSET+=PATCHES
EOF

cat << EOF > /var/db/ports/git/options
_OPTIONS_READ=git-1.8.1.1
_FILE_COMPLETE_OPTIONS_LIST=CONTRIB CURL CVS ETCSHELLS GITWEB GUI HTMLDOCS ICONV NLS P4 PERL SVN
OPTIONS_FILE_SET+=CONTRIB
OPTIONS_FILE_SET+=CURL
OPTIONS_FILE_SET+=CVS
OPTIONS_FILE_SET+=ETCSHELLS
OPTIONS_FILE_UNSET+=GITWEB
OPTIONS_FILE_UNSET+=GUI
OPTIONS_FILE_UNSET+=HTMLDOCS
OPTIONS_FILE_SET+=ICONV
OPTIONS_FILE_SET+=NLS
OPTIONS_FILE_SET+=P4
OPTIONS_FILE_SET+=PERL
OPTIONS_FILE_UNSET+=SVN
EOF

cat << EOF > /var/db/ports/perl/options
_OPTIONS_READ=perl-5.12.4_4
_FILE_COMPLETE_OPTIONS_LIST= DEBUGGING GDBM PERL_MALLOC PERL_64BITINT THREADS PTHREAD MULTIPLICITY SITECUSTOMIZE USE_PERL
OPTIONS_FILE_UNSET+=DEBUGGING
OPTIONS_FILE_UNSET+=GDBM
OPTIONS_FILE_UNSET+=PERL_MALLOC
OPTIONS_FILE_SET+=PERL_64BITINT
OPTIONS_FILE_UNSET+=THREADS
OPTIONS_FILE_SET+=PTHREAD
OPTIONS_FILE_UNSET+=MULTIPLICITY
OPTIONS_FILE_UNSET+=SITECUSTOMIZE
OPTIONS_FILE_SET+=USE_PERL
EOF

cat << EOF > /var/db/ports/curl/options
_OPTIONS_READ=curl-7.24.0
_FILE_COMPLETE_OPTIONS_LIST= CARES CURL_DEBUG GNUTLS IPV6 KERBEROS4 LDAP LDAPS LIBIDN LIBSSH2 NTLM OPENSSL CA_BUNDLE PROXY RTMP TRACKMEMORY
OPTIONS_FILE_UNSET+=CARES
OPTIONS_FILE_UNSET+=CURL_DEBUG
OPTIONS_FILE_UNSET+=GNUTLS
OPTIONS_FILE_SET+=IPV6
OPTIONS_FILE_UNSET+=KERBEROS4
OPTIONS_FILE_UNSET+=LDAP
OPTIONS_FILE_UNSET+=LDAPS
OPTIONS_FILE_SET+=LIBIDN
OPTIONS_FILE_UNSET+=LIBSSH2
OPTIONS_FILE_UNSET+=NTLM
OPTIONS_FILE_SET+=OPENSSL
OPTIONS_FILE_SET+=CA_BUNDLE
OPTIONS_FILE_SET+=PROXY
OPTIONS_FILE_UNSET+=RTMP
OPTIONS_FILE_UNSET+=TRACKMEMORY
EOF

cat << EOF > /var/db/ports/ca_root_nss/options
_OPTIONS_READ=ca_root_nss-3.14.1
_FILE_COMPLETE_OPTIONS_LIST=ETCSYMLINK
OPTIONS_FILE_UNSET+=ETCSYMLINK
EOF

cat << EOF > /var/db/ports/pcre/options
_OPTIONS_READ=pcre-8.31
_FILE_COMPLETE_OPTIONS_LIST=JIT
OPTIONS_FILE_SET+=JIT
EOF


echo "devel/subversion: WITHOUT_MOD_DAV_SVN|WITHOUT_APACHE2_APR" >> /usr/local/etc/ports.conf
echo "devel/apr-svn: APR_UTIL_WITH_BERKELEY_DB=yes" >> /usr/local/etc/ports.conf

cd /usr/ports/devel/git && make install clean 
